### ISSUE TITLE
COCO API on CodaLab servers

### ISSUE THREAD

**Issue by richardaecn** [codalab/codalab-competitions#2119]
Hi,

@FlavioAlexander 

I am the organizer of COCO Detection Challenge https://competitions.codalab.org/competitions/5181 . Recently after the update of CodaLab, I've encountered the following error:

`Traceback (most recent call last):
  File "/tmp/codalab/tmpQ9FeyQ/run/program/run.py", line 36, in 
    from pycocotools.coco import COCO
ImportError: No module named pycocotools.coco`

Can you please make sure that the COCO Python API is installed on the evaluation server? https://github.com/cocodataset/cocoapi/tree/master/PythonAPI 

The Python API can be installed by:
1. "git clone https://github.com/cocodataset/cocoapi.git"
2. run "make" under coco/PythonAPI 
3. run "python setup.py build_ext install" under coco/PythonAPI with superuser permission.

Thanks!

**Comment by ckcollab** [comment]
**If you are familiar with docker and have free time...**
You can actually create a custom docker image for the competition now, adding the new cocoapi dependency:

https://github.com/codalab/docker-codalab-legacy-worker

This is extra handy because it gives participants an easy environment to test with. You then specify this docker image name in your competition settings.

**If not...**
If you are unfamiliar with docker I can add mscoco dependencies no problem! Should only take a couple seconds. If so, would you give me "eric2" admin access to your competition? Also, could you email me eric@ckcollab.com a sample submission to test with?

Apologies for the disruption in your competition, have a good one,
Eric

**Comment by CrazySssst** [comment]
hi , now can i submit my results successfully?

**Comment by ckcollab** [comment]
I added the dependency, this should be fixed now!

**Comment by richardaecn** [comment]
Thanks for your help! @ckcollab

**Comment by richardaecn** [comment]
@ckcollab I just made a sample submission and it still failed with the same error. For a sample submission to test with, can you try to re-run one of the successfully evaluated entries in "val2017 (bbox)" phase? Thanks!

**Comment by ckcollab** [comment]
Did you "re-run" the submission that failed? When you "re-run" it uses the same (old) docker image the submission was ran with, in an attempt to make submission results immutable.

I re-uploaded (not re-running) a submission (bbox) and it appears to be working... apologies for the back and forth :)

**Comment by richardaecn** [comment]
@ckcollab I tried to re-upload and it worked. Thanks for your help!

**Comment by CrazySssst** [comment]
val2017(box) is ok , but  submission failed for test-dev2017(bbox) @richardaecn @ckcollab 

error:
`/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')`
