### ISSUE TITLE
Delete competitions does not work on LRI server

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2173]
I think this bug was fixed, maybe the fix was not pushed to LRI?

**Comment by Tthomas63** [comment]
I believe updating the LRI server also should fix this issue. Tested on some of my competitions and appears to be working.

**Comment by vberger** [comment]
It looks like something happened, because it appears the bug is back. When I try to delete competition 139 on the LRI server, I get this error:

> **The CodaLab site is currently unavailable.**
>
> Sorry, the page you are looking for is currently unavailable.
>
> Please try again later.

**Comment by Tthomas63** [comment]
Hello @vberger,

Thanks for bringing this to our attention. There appears to have been an old database constraint causing an issue. We removed the constraint and deleting competitions seems to be working fine now.

Please let us know if you have any further issues!

Thanks,
Tyler
