### ISSUE TITLE
Last entry displayed instead of best one

### ISSUE THREAD

**Issue by madclam** [codalab/codalab-competitions#2488]
This is regarding competition https://competitions.codalab.org/competitions/20112

Hi, 
I posted this on slack, not sure you have seen it.
I was contacted by Motoki Saitama (“Taka”), he is complaining that his submission 111 with score 0.4923 is on the leaderboard, 
while his submission 110 with score 0.5080, submitted a few hours earlier is not.
So this is strange, the leaderboard should show the best right, not the latest ? Is this a bug or a configuration ? 
A few hours later he submitted 112 which is both more recent and better, so this cannot be demonstrated anymore but I did see this myself, and I attach the screen shot he sent me.

And in fact, scrutinizing the submission table right now I see exactly the same problem with cloukitchen, these are his best submissions
cloudkitchen,0.6400 (18),0.844 (26),0.01 (12),976.27 (37),19.53 (37),1029.00 (27),static,2018-12-24 14:34:22.766828+00:00,my_submission.zip,False
cloudkitchen,0.6389 (19),0.860 (19),0.01 (17),1348.08 (41),26.96 (41),1408.00 (31),Removed Pruning,2018-12-10 14:44:41.088064+00:00,my_submission.zip,False
cloudkitchen,0.6362 (20),0.851 (23),0.01 (10),1166.60 (39),23.33 (39),1225.00 (29),,2019-01-03 09:02:17.671104+00:00,my_submission.zip,True

but on the leaderboard we see cloud kitchen with score ,0.6362 which is the latest submission but not his best (0.6400)

Thanks
David

**Comment by dhrou** [comment]
hi, any ETA ?

**Comment by Tthomas63** [comment]
Hello @dhrou,

I will be taking a look at this within the next few days and should have a solution before the week-end.

Best regards,
Tyler

**Comment by Tthomas63** [comment]
Hello all,

Quick update we've identified the issue and have a PR up that should correct the logic:
https://github.com/codalab/codalab-competitions/pull/2499/files

There's still an issue we're looking into with the front-end adding the `submitted to leaderboard` checkmark on submissions that are not added to leaderboard.

Best regards,
Tyler

**Comment by sapna13** [comment]
I have the same issue with my SemEval competition.
https://competitions.codalab.org/competitions/19955

We have a deadline to post the results coming week, and we have promised for a best submission leaderboard. Didn't see this coming.

**Comment by Tthomas63** [comment]
Hello All,

This should be fixed now. All future submissions that are better should automatically be added to the leaderboard. Please let me know if you encounter any issues and I will take a look.

Best regards,
Tyler

**Comment by dhrou** [comment]
Hi, 
Could this be reopened ? 
There is still an issue, a more recent entry with a better score is not on the LB:
 
Looking at the leaderboard right now 6th Feb 2019 14:49 one can see in second position : 
2 cloudkitchen 02/04/19 0.8469

However if one look at the CSV one see this two entries: 

cloudkitchen | 0.8524 (16) | 0.916 (14) | 0.01 (47) | 454.25 (55) | 9.08 (55) | 501.00 (42) | graph150 | 2019-02-05 14:25:31.225283+00:00 | my_submission.zip | False
==>higher score AND more recent, not on LB

cloudkitchen | 0.8469 (17) | 0.905 (19) | 0.01 (39) | 385.01 (41) | 7.70 (41) | 431.00 (29) | optimized cuts | 2019-02-04 11:27:50.617184+00:00 | my_submission.zip | True
==>lower score AND less recent, on LB !

Thanks for looking into this
David

**Comment by dhrou** [comment]
…there is still a problem, I appended a comment in the issue
thanks
David
-----------------------------------------------------------------------------------------------------
|     David Rousseau        rousseau@lal.in2p3.fr <mailto:rousseau@lal.in2p3.fr>   skype:droussea <skype:droussea>                 |
|   LAL-Orsay, U Paris-Sud, CNRS/IN2P3, Université Paris-Saclay, France   |
|  snail:  LAL, CSO Orsay, Bat 200,  BP 34, 91898 Orsay Cedex.                   |
|  @ LAL     :  Bat 200 Pièce 142 : +33 (0)1 64 46 85 91                                 |
|  @ CERN :  40/1-D12                : +41 (22) 76 73857                                    |
-----------------------------------------------------------------------------------------------------

**Comment by Tthomas63** [comment]
Hello @dhrou,

Sorry for the belated response, I took a look again, and I think this is due to the leaderboard config with the competition at the moment.

The `score` column is currently set to `descending`, meaning a lower score is considered better, so with the last submission from `cloudkitchen`, you noted his lower scored submission that was less recent was added to the leaderboard, but not his most recent higher scored submission.

Changing the sorting order of the `score` column to `ascending` should give you the behavior you expect, but I'm un-sure if this will cause un-intended consequences with leaderboard positions. 

Best regards,
Tyler

**Comment by dhrou** [comment]
Tagging @victor-estrade who has set up the competition.
This not possible, if one looks at the LB right now, entry 1 2 3 4 are ordered with #1 having the highest score, #2 lower etc... Unless this was changed very recently which would be a mistake for sure.

**Comment by victor-estrade** [comment]
I tried to set the `score` column to ascending and it put the poeple with score -1 as the best ones which is the opposite of a good score.
`descending` will put high score as best ones. The issue seems to lie elsewhere.

**Comment by victor-estrade** [comment]
Now our 2 best participants have submitted (slightly) better solutions and the leaderboard is showing their old submission. It seems that the leaderboard is not updated anymore.

**Comment by madclam** [comment]
The problem persists for competition https://competitions.codalab.org/competitions/20112

It is supposed to show the best submission on the leaderboard, but e.g. fastback’s last submission 09/02/19 #541038 has a better score than that shown on the leaderboard.

<img width="910" alt="screen shot 2019-02-13 at 4 48 29 pm" src="https://user-images.githubusercontent.com/7594063/52724532-cefd4d80-2faf-11e9-9987-0b585b6849d2.png">
<img width="898" alt="screen shot 2019-02-13 at 8 00 21 am" src="https://user-images.githubusercontent.com/7594063/52724533-cefd4d80-2faf-11e9-8bf3-72550a2fa353.png">

**Comment by Tthomas63** [comment]
Hello all,

Apologies I seem to have misunderstood the issue. This should be fixed now and we should have tests to catch this in the future.

If you'd like to force old submissions to the leaderboard, re-running them from the submissions page should work.

Please let me know if you encounter anymore problems.
Best regards,
Tyler

**Comment by dhrou** [comment]
OK many thanks, Victor has rerun the one which were behind.

Now : for the one with 0 score, how are they ordered ? It looks a bit random.
I would suggest to order on increasing accuracy, to give a bonus to the one who are not just submitting the starting kit.
Would this be possible ? (just talking for now)
David

-----------------------------------------------------------------------------------------------------
|     David Rousseau        rousseau@lal.in2p3.fr <mailto:rousseau@lal.in2p3.fr>   skype:droussea <skype:droussea>                 |
|   LAL-Orsay, U Paris-Sud, CNRS/IN2P3, Université Paris-Saclay, France   |
|  snail:  LAL, CSO Orsay, Bat 200,  BP 34, 91898 Orsay Cedex.                   |
|  @ LAL     :  Bat 200 Pièce 142 : +33 (0)1 64 46 85 91                                 |
|  @ CERN :  40/1-D12                : +41 (22) 76 73857                                    |
-----------------------------------------------------------------------------------------------------

**Comment by dhrou** [comment]
The original problem is still there !
E.g fastrack 16th Feb submission is on the LB  despite having a smaller score that 9th Feb 
fastrack,1.0533 (1),0.941 (2),0.00 (69),99.56 (21),1.99 (21),137.00 (9),,2019-02-09 00:28:44.390934+00:00,submission_09_02_2019.zip,False
fastrack,1.0510 (2),0.942 (1),0.00 (74),104.81 (22),2.10 (22),141.00 (10),,2019-02-16 21:38:29.867538+00:00,submission_16_02_2019.zip,True
f
same for cloudkitchen

**Comment by Tthomas63** [comment]
Hello David,

We looked into this, and it seems that submission is from before we deployed the last fix which worked on 02/13/19. It should be able to be re-ran, but it may not get the same score. 

The fix won't automatically put old submissions on the leaderboard, only by re-running them, which creates a new submission that does not count towards totals with the same data as the old submission, should the problem be solved. It should also be possible for us to force a submission to the leaderboard manually if needed.

Best regards,
Tyler

**Comment by dhrou** [comment]
OK I understand. The thing is that there is a 5% spread in the time measurement (rerunning the exact same code). We know about this; if some participants are very close at the end of the competition, we will rerun many time and average. But for now, if we rerun the risk is to get a different result. If possible, it would be better/easier to just force the few on the leaderboard as you suggest.

**Comment by victor-estrade** [comment]
I forced the submissions on the leaderboard.

**Comment by Tthomas63** [comment]
Hello All,

Sorry for the inconveniences, please let us know if there's anymore we can do to help.

Best regards,
Tyler

**Comment by dhrou** [comment]
I believe this can be closed, thanks.

**Comment by ckcollab** [comment]
:+1:
