### ISSUE TITLE
Planti of Submissions Faild 

### ISSUE THREAD

**Issue by litian1045** [codalab/codalab-competitions#2983]
Hi, we are the organizers of WebFace260M Track of ICCV21-MFR (https://competitions.codalab.org/competitions/32478) and thank you for your work on the Codalab so we can hold our competition on your platform.

We recently received a lot of reflections that many participants can not upload their submissions to the Codalab, however, we don't know which part of the system made this problem happen. Could you please help us to check if this was caused by any issues in the Codalab?

Thank you very much
Regards,
Tian

**Comment by TangChangcheng** [comment]
I encountered the same problems that it shows "failed to upload" after submitting

**Comment by michalmonday** [comment]
I have the same problem with:
https://competitions.codalab.org/competitions/20794#participate

It worked well up to yesterday.

I tried different browsers, PC with home wifi, then smartphone with mobile data, but attempting to upload results always ends with "Sorry, failed to upload a file"

**Comment by Yzj1030** [comment]
I have the same problem with:
https://competitions.codalab.org/competitions/20128#participate-submit_results

**Comment by lywcn** [comment]
"Failed to upload a file" error for https://competitions.codalab.org/competitions/21238

**Comment by lxtGH** [comment]
I have the same problem with: https://competitions.codalab.org/competitions/20128#participate-submit_results

**Comment by jack57lee** [comment]
I have the same problem with: https://competitions.codalab.org/competitions/24122

**Comment by paul007pl** [comment]
We got the same issue, and please also help our MVP competition:
https://competitions.codalab.org/competitions/33430

**Comment by BDonnot** [comment]
We have the same issue on the "L2RPN" competitions. Submission weighting more than a few kB cannot be uploaded with the error below:
<img width="460" alt="Screen_Shot_2021-08-29_at_11 20 51_pm" src="https://user-images.githubusercontent.com/9463182/131301566-d8f7039d-ab51-4bc5-a3f9-f21e97897926.png">

It impacts pretty much all participants.

**Comment by rjbruin** [comment]
Same here!

**Comment by acletournel** [comment]
There is a resource shortage on the storing device. Problem is under investigation. We'll keep you informed

**Comment by Andrew-Brown1** [comment]
@acletournel is there any update or timeline on the problem?

**Comment by wulala-source** [comment]
I have the same problem with: https://competitions.codalab.org/competitions/32360#participate-submit_results

**Comment by wangll1212** [comment]
"Failed to upload a file" error for https://competitions.codalab.org/competitions/32360

**Comment by rangsimanketkaew** [comment]
Now it seems the issue is fixed for me.

**Comment by acletournel** [comment]
problem has been solved. Sorry for the inconvenience

**Comment by rjbruin** [comment]
A user of my competition is still having issues related to disk space, specifically in that the Docker image we are using does not have enough space to be downloaded:

https://github.com/VIPriors/vipriors-challenges-toolkit/issues/24

**Comment by rjbruin** [comment]
The issue does not seem to be fixed. Aside from the docker container issue, I have another contestant saying they got the "cannot upload submission" error.

**Comment by rjbruin** [comment]
I'm still getting users that cannot submit to our competition:

```
docker: failed to register layer: Error processing tar file(exit status 1): write /opt/conda/lib/libmkl_vml__mc2.so: no space left on device.
```

**Comment by Didayolo** [comment]
> I'm still getting users that cannot submit to our competition

What is your competition?

If you are the only one still having the problem, you should maybe create a new Github issue and give more information about your case.
