### ISSUE TITLE
Can't submit results on the new site

### ISSUE THREAD

**Issue by yk-pku** [codalab/codalab-competitions#3220]
The competition of "The 2nd Large-scale Video Object Segmentation Challenge - Track 1: VOS (migrated server)" can not evaluate results now. The website is https://codalab.lisn.upsaclay.fr/competitions/6066#learn_the_details. All submission files are failed which can be evaluated normally on the previous website.

**Comment by yk-pku** [comment]
I found the new website is organized by LinjieY, but I can't find any corresponding contact information

**Comment by BrandaZhao** [comment]
I meet the same problem. I want to submit the result of COCO Detection (Bounding Box) test-dev. But the phase is closed.

**Comment by HB-X** [comment]
> 

I have the same problem.

**Comment by GingerCohle** [comment]
Same problem, pls update the website, TY!

**Comment by yk-pku** [comment]
Thanks LinjieK very much. The current new website is working, please feel free to close this issue

**Comment by zhuhaifengaaa** [comment]
I have the same problem.

**Comment by Shallow2000** [comment]
I have the same problem.

**Comment by Didayolo** [comment]
Hello everybody,

Can you please provide more information?

- Is there only one competition (The 2nd Large-scale Video Object Segmentation Challenge) that have an issue or is there multiple competitions?
- What are the symptoms?

**Comment by BrandaZhao** [comment]
> 

The competition of "RVC Challenge: COCO Detection (Bounding Box)" on "test-dev2022(bbox)"(https://codalab.lisn.upsaclay.fr/competitions/6420#participate-submit_results) still can not evaluate results. It is claimed that "This phase of the competition is closed."

**Comment by alpc111** [comment]
I meet a question in The competition of "RVC Challenge: COCO Detection (Bounding Box)" on "test-dev2022(bbox)"
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Execution time limit exceeded!

**Comment by Didayolo** [comment]
Hello @BrandaZhao and @alpc111,

I think these problems are linked to the settings of the competitions. COCO organizers can change that easily using the competition editor.

> The competition of "RVC Challenge: COCO Detection (Bounding Box)" on "test-dev2022(bbox)"(https://codalab.lisn.upsaclay.fr/competitions/6420#participate-submit_results) still can not evaluate results. It is claimed that "This phase of the competition is closed."

I guess the dates of the phases are not right.

> WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Execution time limit exceeded!

I guess the time limit is not right.

Please contact directly COCO organizers so they are aware of these problems.

**Comment by HB-X** [comment]
Hello every one, the new website (https://codalab.lisn.upsaclay.fr/competitions/7384#participate) can submit the submissions.

**Comment by Didayolo** [comment]
Great :-)

I close this issue as I think it is solved. Please re-open it or re-create a new one (with detailed information) if you face any problem again.

**Comment by cancam** [comment]
Hello everyone,

The time limit issue still seems valid for the mask detection task (https://codalab.lisn.upsaclay.fr/competitions/7383#learn_the_details). How should I reach COCO organizers regarding this issue? 


> I meet a question in The competition of "RVC Challenge: COCO Detection (Bounding Box)" on "test-dev2022(bbox)" WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. /opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment. warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.') Execution time limit exceeded!
