### ISSUE TITLE
TLS certificate expired

### ISSUE THREAD

**Issue by keisuke198619** [codalab/codalab-competitions#3576]
Hi CodaLab team,

When visiting https://codalab.lisn.upsaclay.fr/competitions I receive a browser security warning:
Your connection is not private
NET::ERR_CERT_DATE_INVALID

Because the TLS certificate appears to be expired, users cannot load the competitions page or submit entries.

Could you please renew the certificate (e.g., rerun certbot or your usual renewal process) or otherwise update the certificate chain?

Thanks in advance for looking into this!

**Comment by kamdkslansgka** [comment]
+1

**Comment by ObadaS** [comment]
Hello, it should now be fixed.
Sorry for the inconvenience.

**Comment by keisuke198619** [comment]
@ObadaS Much appreciated! I confirmed it worked.

**Comment by Yinlipp** [comment]
@ObadaS 
Thank you for updating the certificate！
As the organizers, we have noticed that even when a correct result file is submitted, the platform still shows it as failed without any relevant error message. The SIZE (BYTES) field shows -1, which suggests that the result file was not successfully read by the platform.
Additionally, clicking on "View scoring output log" or "View scoring error log" leads to a 404 error page.

Could you please help us check this issue?
